### PR TITLE
Businesses Page Release and quite a few improvements

### LINKED ISSUE #48: Add Instagram Icon
Add Instagram Icon into the webpage

_Design Material_ https://www.figma.com/file/cIO2cMtbZ8FVjUfNucKJCF/join.circles.net?node-id=3991%3A579

LINK TO INSTA ACCOUNT: https://www.instagram.com/circles_ubi_official/

### LINKED ISSUE #49: Add bussines section
We need to add a new Tab/ section: Bussines.

_Design Material_ https://www.figma.com/file/cIO2cMtbZ8FVjUfNucKJCF/join.circles.net?node-id=3819%3A19830

LINKS:
_Embbeded video Link_ https://vimeo.com/469130953/06edd440b2

_FAQ button:_ https://joincircles.net/faq
_Handbook button:_ https://handbook.joincircles.net/
_Telegram button_ https://t.me/CirclesBazaar

### LINKED ISSUE #50: FAQs screen  is Croped.
The FAQ screen does not fit the screen. There are two white colums on each side. And the Social media icons are croped.

Browser: Mozilla, Safari, Chromium.

Screenshot 2021-08-04 at 20 11 56

### LINKED ISSUE #53: The README.md file mentions wrong dev server port 3000 or 8080
_**Describe the bug**_
The README.md file says the dev server runs on port 3000, while in package.json the port is set to 8080. Which is the right port? ;-)

### LINKED ISSUE #55: Erase the Donation information
We can erase the Donation infomration from our landing page, as well as the button from the menu. 
Instead we will for now add a small text which is a description we are also using on the new communicational Material.

_Design Material_ https://www.figma.com/file/cIO2cMtbZ8FVjUfNucKJCF/join.circles.net?node-id=4079%3A6

### PR DESCRIPTION
**Pull request by eminx**
So with this PR, we are addressing quite a few issues.

Closes #48 
Closes #49 
Closes #50
Closes #53 
Closes #55 

The preview page can be seen here: https://preview.joincircles.net/businesses

### CODE REVIEW

**Review by llunaCreixent — COMMENTED** [review]
Very nice!! thanks @eminx !
I didn't see the translations working, though.

**Review by louilinn — COMMENTED** [review]
Great! 
Some minor UX things:
The spacing on the business page seems a little off from the design
The circles vs bitcoin section especially. The network image goes outside the white circle on mobile view and the circle becomes very large in website fullscreen. Also a long space after this section.

And yes as lluna also mentioned the translation is not done. Do we want that before we merge?

Code changes looks good to me :star:

**Comment by louilinn** [comment]
Another thing: the donation page is still sopped to be at joincircles.net/en/donate or not reachable? It is still there if you have the link

**Comment by eminx** [comment]
> I didn't see the translations working, though.

Which translations do you mean? For the business page, there are no translations available and I actually had asked for it, but they said we'll release only in English...

@llunaCreixent 

Thanks for the review also!

**Comment by eminx** [comment]
> Another thing: the donation page is still sopped to be at joincircles.net/en/donate or not reachable? It is still there if you have the link

The translation tool we're using doesn't really work with `/en` since english is default. But other langs do work. So for english, joincircles.net/donate

@louilinn 

Thanks!

**Comment by eminx** [comment]
> The spacing on the business page seems a little off from the design
> The circles vs bitcoin section especially. The network image goes outside the white circle on mobile view and the circle becomes very large in website fullscreen. Also a long space after this section.

This I'm aware and have consulted to Lucia about prior to making it. There's not much to do with the spacing if we want to pursue certain design effects in all screens, such as the perfect circle cut on the sides, behind the vs-bitcoin section...

About:
> The network image goes outside the white circle on mobile view

Could you please upload a screenshot and tell me what device/os/browser you're using @louilinn ?
I checked it on different devices and it was fine on my end but I perhaps missed something..
Thanks!

**Comment by louilinn** [comment]
> Could you please upload a screenshot and tell me what device/os/browser you're using @louilinn ?
> I checked it on different devices and it was fine on my end but I perhaps missed something..
> Thanks!

I think it is ok probaly. It was using dev tools in firefox and now i can't reproduce it so it's probably nothing..

Regarding the donation page I was refering to whether the donation page should still be up on https://joincircles.net/donate or if that route should no longer exist

**Comment by eminx** [comment]
> I think it is ok probaly. It was using dev tools in firefox and now i can't reproduce it so it's probably nothing..

Aha OK then it's normal. You probably manually changed the size of the window right? Then it messes up but on the first page load, it checks the screen width and height of the container and accordingly locates svg background image behind. But when user changes the width of the browser, this doesn't re-run...

> Regarding the donation page I was refering to whether the donation page should still be up on https://joincircles.net/donate or if that route should no longer exist

Yes, the donation page will remain, we just removed the main menu link to the page... 

@louilinn

**Comment by eminx** [comment]
@louilinn & @llunaCreixent feel free to approve the review if/when you don't have any other concerns... :)

**Comment by llunaCreixent** [comment]
> > I didn't see the translations working, though.
> 
> Which translations do you mean? For the business page, there are no translations available and I actually had asked for it, but they said we'll release only in English...
> 
> @llunaCreixent
> 
> Thanks for the review also!

Understood!
In that case, the translation PR (https://github.com/CirclesUBI/circles-website/pull/47) is not really closed by this PR, right?

**Comment by eminx** [comment]
> In that case, the translation PR (#47) is not really closed by this PR, right?

Oh that's true! I mixed up the issues... It was #50 instead of #47

Corrected now! Thanks! @llunaCreixent

**Review by llunaCreixent — DISMISSED** [review]
I'm happy now :)

**Review by louilinn — DISMISSED** [review]

**Review by houndbee — DISMISSED** [review]

**Comment by eminx** [comment]
I just made some updates so need an approving review again pls 🙏 

@houndbee @louilinn @llunaCreixent

**Review by llunaCreixent — APPROVED** [review]
Nice job @eminx and @triaslucia !!

**Pull request merged**
